### ISSUE TITLE
Favorites rearange 

### ISSUE THREAD

**Issue by michalrzak** [memoriesadrift/we-find#77]
Right now the favorites are displayed in one column in very big buttons. This in my opinion is quite wasted space. We should:
 * make the buttons smaller
 * arrange them in a 2 column setup

**Comment by memoriesadrift** [comment]
It's really difficult to size the buttons so that the text fits into them. If you have for example "VU Modellierung" that fits neatly into a 100 x 100 button. However "PS 3D-Laserscanning - Methods, Modeling and Fields of Application" doesn't. Having different sized buttons would be weird, so I went with a larger size.
As for the second issue, that shouldn't be too difficult to implement, imo just a builder that takes 2 widgets at a time and puts them into a row.

**Comment by michalrzak** [comment]
actually forgot to assign my self and am working on this rn
